language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install: 
  - pip install -U -r requirements.txt

deploy:
  provider: pypi
  user: "thiagorpereira"
  password: "#thiago96#"
  distributions: "sdist bdist_wheel"
  on:
    branch: master